deployment:
  tasks:
    - export DEPLOYPATH=/home/studs4you/public_html
    - /bin/mkdir -p $DEPLOYPATH/wp-content/themes/petslist-raushan
    - /bin/rsync -a wp-content/themes/petslist-raushan/ $DEPLOYPATH/wp-content/themes/petslist-raushan/
    - /bin/cp favicon.ico $DEPLOYPATH/favicon.ico
    - /bin/cp apple-touch-icon.png $DEPLOYPATH/apple-touch-icon.png
    - /bin/cp setup-studs4you.php $DEPLOYPATH/setup-studs4you.php
    - /bin/cp purge-cache.php $DEPLOYPATH/purge-cache.php
    - /bin/cp studs4you_db.sql $DEPLOYPATH/studs4you_db.sql
